version: "3"

services:
  redis-server:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - nest-app
  myapp:
    build: .
    ports:
      - "5000:8080"
    networks:
      - nest-app

networks:
  nest-app:
    driver: bridge
